name: Pascal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Lazarus Environment
        uses: gcarreno/setup-lazarus@v2.2.9
        with:
          lazarus-version: "dist"
      - name: Build The Main Application 
        run: lazbuild ./src/main/main.lpi
